### ISSUE TITLE
Add some way to provide "lightweight" styling to xaml controls

### ISSUE THREAD

**Issue by acoates-ms** [asklar/react-native-xaml#21]
Maybe add a way to apply resources to the xaml control, such as:

```jsx
<NativeXamlControl 
    type="Button"
    content="Hello"
    ResourceButtonForegroundPressed={PlatformColor('SystemControlAcrylicWindowBrush')}
    ResourceButtonForeground="red" />
```

Which would be mapped roughly to this XAML (created by code rather than markup obviously)
```xml
<Button>
  <Button.Resources>
       <StaticResource x:Key="ButtonForegroundPressed" ResourceKey="SystemControlAcrylicWindowBrush"/>
       <SolidColorBrush x:Key="ButtonForeground" Color="red"/>
  </Button.Resources>
  <Button.Content>Hello</Button.Content>
</Button>
```

**Comment by asklar** [comment]
@acoates-ms thanks for filing this! 
Another option would be to say:
```jsx
<NativeXamlControl 
    type="Button"
    content="Hello" Resources={{ 
        buttonForegroundPressed: PlatformColor('SystemControlAcrylicWindowBrush');
        buttonForeground="red"
      }} />
``` 

If one wanted to have a shared theme across the app, one could define such a dictionary in JS:

function getTheme() { return { ... }; }

then use it thusly:
```jsx
[themeObj, setTheme] = useState(getTheme());
// hook up OnThemeChanged to call setTheme(getTheme())

<NativeXamlControl 
    type="Button"
    content="Hello" Resources={{ ...themeObj,
        buttonForegroundPressed: PlatformColor('SystemControlAcrylicWindowBrush');
        buttonForeground="red"
      }} />
``` 

Do you think that'd be acceptable? Mainly looking to avoid adding properties if we don't have to, for perf reasons (runtime + binary size)

**Comment by acoates-ms** [comment]
Its probably reasonable.
The down side to having a single JS property, is that if you change one property within the resources, the whole property needs to be sent over and all the logic to handle all the resources on the native side would run.  So long as we dont put anything in there that we expect the app to be changing then it should be ok.

**Comment by asklar** [comment]
I've been experimenting with this here: https://github.com/asklar/react-native-xaml/tree/styling
The challenge is that XAML does not have dynamic resources like WPF did, so once you set a ResourceDictionary on an element, its children won't be notified if you change anything about the dictionary (either set a new RD, or add/remove/change brushes inside of it). They only get one chance to query the RD when the RD is set on the parent and that's it. This was a sad realization today after talking to markup team. See https://github.com/microsoft/microsoft-ui-xaml/issues/4443
