### ISSUE TITLE
NavigationView example

### ISSUE THREAD

**Issue by jeanmaried** [asklar/react-native-xaml#51]
Could you please provide an example of how to setup a simple NavigationView with a few NavigationViewItems? I'm racking my brain and can't figure out how this is expected to done. What props are needed and how it should be it be structured would be super helpful.

Currently I have this which crashes the app instantely:

```
      <NavigationView
        name="nvSample5"
        height={460}
        header={{string: 'This is Header Text'}}
        paneDisplayMode={NavigationViewPaneDisplayMode.Auto}
        isTabStop={false}
        onSelectionChanged={(event: NativeSyntheticEvent<undefined>) => {}}>
        <NavigationViewItem content={{string: 'Menu Item1'}} />
        <NavigationViewItem content={{string: 'Menu Item2'}} />
      </NavigationView>

**Comment by achipa** [comment]
Same here. As react-native-xaml is a codegen-based thin wrapper, I'd expect to have a very close to 1:1 mapping with existing xaml strictures/code. For example if I had:

```xaml
<Grid>
    <NavigationView>
        <NavigationView.MenuItems>
            <NavigationViewItemHeader Content="Main"/>
            <NavigationViewItem Content="Customers"/>
            <NavigationViewItem Content="Orders"/>
            <NavigationViewItemSeparator/>
            <NavigationViewItemHeader Content="Reports"/>
            <NavigationViewItem Content="Customers"/>
            <NavigationViewItem Content="Orders"/>
            <NavigationViewItem Content="Sales"/>
            <NavigationViewItemSeparator/>
            <NavigationViewItemHeader Content="Charts"/>
            <NavigationViewItem Content="Sales by Customer"/>
            <NavigationViewItem Content="Sales by Product"/>
            <NavigationViewItem Content="Sales by Date"/>
        </NavigationView.MenuItems>
    </NavigationView>
</Grid>
```

I would expect to end up with something like 

```tsx
<Grid>
    <NavigationView>
        <NavigationView.MenuItems>
            <NavigationViewItemHeader content={{string: "Main"}}/>
            <NavigationViewItem content={{string: "Customers"}}/>
            <NavigationViewItem content={{string: "Orders"}}/>
            <NavigationViewItemSeparator/>
            <NavigationViewItemHeader content={{string: "Reports"}}/>
            <NavigationViewItem content={{string: "Customers"}}/>
            <NavigationViewItem content={{string: "Orders"}}/>
            <NavigationViewItem content={{string: "Sales"}}/>
            <NavigationViewItemSeparator/>
            <NavigationViewItemHeader content={{string: "Charts"}}/>
            <NavigationViewItem content={{string: "Sales by Customer"}}/>
            <NavigationViewItem content={{string: "Sales by Product"}}/>
            <NavigationViewItem content={{string: "Sales by Date"}}/>
        </NavigationView.MenuItems>
    </NavigationView>
```
...which is not really doable right now (no apparent way of defining/adding NavigationView.MenuItems, for starters)

**Comment by asklar** [comment]
Good request! Definitely would love to have specific jsx examples.

Right now codegen looks at the type of properties as well as whether the property is backed by a DependencyProperty in order to decide what to project; moreover sub-items need custom logic to map children to the right collection property. 

(FYI you would not use the NavigationView.MenuItems property, you'd just create the NavigationViewItem/Header/Separator directly inside of the NavigationView tag)

This is all possible for NavigationView, I'll get back in a couple of days :) Keep the feedback coming!

**Comment by asklar** [comment]
Good bug, thanks again for filing. I just got it to work!

![image](https://user-images.githubusercontent.com/22989529/112403222-417ea280-8ccb-11eb-8eac-b9100e5ddb4b.png)

**Comment by asklar** [comment]
@achipa @jeanmaried See [USAGE.md](https://github.com/asklar/react-native-xaml/blob/main/USAGE.md)

**Comment by jeanmaried** [comment]
@asklar awesome! Thank you.
