### ISSUE TITLE
BitmapIcon with uriSource crashing app

### ISSUE THREAD

**Issue by jeanmaried** [asklar/react-native-xaml#62]
👋🏻 I'm trying to use a BitmapIcon like so:
```
<BitmapIcon uriSource="./home.svg" />
```
This crashes the app. I tried with a png too and same result.

**Comment by asklar** [comment]
can you show more of your jsx / what is the bitmap icon parented to?

**Comment by jeanmaried** [comment]
He's all by himself:
```
const App = () => {
  return (
    <View>
      <BitmapIcon uriSource="./home.svg" />
    </View>
  );
};
```

**Comment by asklar** [comment]
So I don't think `./` style APIs would work here, as XAML expects a specific format of URI, either http, or an ms-appx (for assets embedded in the app) or  ms-appdata.
I don't get a crash when using a http uri, but the image doesn't render... still investigating.

**Comment by asklar** [comment]
Ok got it to work:
![image](https://user-images.githubusercontent.com/22989529/113364860-7319ee00-9309-11eb-9b21-1d0c9ccc80e0.png)

Notes:
- it must be a valid URI, not a local reference like './foo.bar'
- it must be a bitmap, an SVG is not a bitmap
- you have to set the "don't display this as monochrome" which is the default for XAML, for some reason.
```jsx

const App = () => {
  return (
    <View>
      {/* <BitmapIcon uriSource="./home.svg" /> */}
      <BitmapIcon uriSource="https://microsoft.github.io/react-native-windows/img/homepage/cross-platform.png" showAsMonochrome={false} width={50} height={50} />
    </View>
  );
};
```

**Comment by jeanmaried** [comment]
Ah ok thanks for the info. How would you go about using a local image then?

**Comment by asklar** [comment]
You can put the file under your app's Assets folder. Then if you open the `.sln` file in visual studio, you can add the local image to the app's Assets folder (right click the folder, Add existing item, navigate to Assets\file.png

![image](https://user-images.githubusercontent.com/22989529/113437882-51b61200-939c-11eb-912e-db120877d1f1.png)

Then in your jsx:
```jsx
        <BitmapIcon uriSource="ms-appx:///Assets/cross-platform.png" width={60} height={60} showAsMonochrome={false} />
```

**Comment by asklar** [comment]
see https://docs.microsoft.com/en-us/windows/uwp/app-resources/images-tailored-for-scale-theme-contrast#reference-an-image-or-other-asset-from-xaml-markup-and-code
