### ISSUE TITLE
Displaying content of app when using NavigationView

### ISSUE THREAD

**Issue by jeanmaried** [asklar/react-native-xaml#63]
I have the NavigationView working but now I'm wondering where I put the actual contents of my app. In my case I would like to place a Stack.Navigator from `react-navigation` as the root of my app:
```
<SafeAreaView>
  <View>
    <Stack.Navigator headerMode="none" initialRouteName={'hello'}>
      <Stack.Screen name={'hello'} component={HelloView} />
      <Stack.Screen name={'about'} component={AboutView} />
    </Stack.Navigator>
  </View>
</SafeAreaView>
```
Is there a xaml element I should be using to wrap this and where should it be placed:
```
const App = () => {
  return (
    <NavigationContainer> // from react-navigation
      <NavigationView
        paneDisplayMode={NavigationViewPaneDisplayMode.LeftCompact}
        style={{height}}
        openPaneLength={300}
        isBackButtonVisible={NavigationViewBackButtonVisible.Collapsed}>
        <NavigationViewItemHeader content={{string: 'header'}} />
        <NavigationViewItem content={{string: 'item 1'}}>
          <FontIcon glyph="&#xE790;" />
        </NavigationViewItem>
        <NavigationViewItem content={{string: 'item 2'}}>
          <FontIcon glyph="&#xE790;" />
        </NavigationViewItem>

       // Does it go here inside the NavigationView?

      </NavigationView>

      // or here alongside the NavigationView?

    </NavigationContainer>
  );
};
```
From what I am seeing and the way it is currently behaving it does look like the App content should be in the NavigationView for the different pane modes to work nicely with the content. I have tried a Frame element and that made the app crash.

Sorry for all the questions, I am not very familiar with xaml.

**Comment by asklar** [comment]
full disclosure, I'm not familiar with Stack.Navigator :) From what I gather, it works by showing/hiding views?

In general XAML elements can only have other XAML elements as children (that is, either elements from react-native-xaml, or native controls that are created by RNW or one of the community modules that uses native UI elements like other RNW controls). I'm not sure what would happen if you tried adding a Stack.Navigator element inside. 

I did find a bug in react-native-xaml that I'll fix to enable you to set content in the navigation view control
```jsx
<NavigationView style={{width:1500, height: 400}} >
    <NavigationViewItem content={{ string: "item 1" }} >
      <FontIcon glyph="&#xE790;" />
    </NavigationViewItem>
    <NavigationViewItem content={{ string: "item 2" }} />
    <StackPanel>
      <Text>hello there</Text>
    </StackPanel>
  </NavigationView>
```
