### ISSUE TITLE
Overwrite theme defaults

### ISSUE THREAD

**Issue by jeanmaried** [asklar/react-native-xaml#66]
For example, in my case I want to overwrite the default background color of the NavigationView pane. There is no property for doing this directly and it seems the proper way is through theming (correct me if I'm wrong). However I do not see any way to change the theme default resources at the moment.

**Comment by asklar** [comment]
You can achieve some of that through "lightweight styling": 
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-styles#lightweight-styling

essentially this boils down to looking at the theme brushes/colors used in generic.xaml by the control you're interested in and then you can overwrite those keys in react-native-xaml (there is a lightweight styling example in the usage guide in the repo).

**Comment by jeanmaried** [comment]
Perfect that is what I was looking for. Thank you!
