### ISSUE TITLE
HyperlinkButton Alignment Defaults to Center

### ISSUE THREAD

**Issue by chiaramooney** [asklar/react-native-xaml#73]
The HyperlinkButton in react-native-xaml defaults to centered alignment. Looking at the Xaml Controls Gallery, it appears that the XAML HyperlinkButton defaults to left alignment. Is it possible for the default alignment in react-native-xaml to match that of XAML?

**Comment by asklar** [comment]
From https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.control.horizontalcontentalignment:
> Each control might apply this property differently based on the Style setters for the control's implicit style, and its visual template. Also, the apparent "default value" of each individual control used in UI can be different. For example, a Button control starts with the value Center.

react-native-xaml is just exposing whatever the default behavior for the control is, so it might be that HyperlinkButton is opting to be center aligned by default (as it is a subclass of ButtonBase); so it might be that Xaml Controls Gallery styles its hyperlinks with a non-default `HorizontalContentAlignment=Left`, in which case you can do the same in react-native-xaml. Can you check if that works for rngallery?

**Comment by asklar** [comment]
looks like the center alignment is coming from the View that the hyperlinkButton is being wrapped within (i.e. app issue), so closing this for the time being
