### ISSUE TITLE
Border missing cornerRadius property

### ISSUE THREAD

**Issue by dstaley** [asklar/react-native-xaml#83]
`<Border>` is missing its `cornerRadius` property.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.border.cornerradius?view=winrt-20348#Windows_UI_Xaml_Controls_Border_CornerRadius

**Comment by asklar** [comment]
are you able to achieve this with the `borderRadius` RN property?  https://reactnative.dev/docs/view-style-props#borderradius

**Comment by dstaley** [comment]
No, adding `style={{borderRadius: 8}}` has the same result as #84
