### ISSUE TITLE
Applying a bottom margin to a TextBlock results in an unhandled Win32 exception

### ISSUE THREAD

**Issue by dstaley** [asklar/react-native-xaml#84]
Trying to render

```jsx
<TextBlock
  text="USPS"
  margin={{top: 0, right: 0, bottom: 8, left: 0}}
/>
```

results in an unhandled Win32 exception. Unfortunately my Visual Studio skills aren't good enough for me to figure out exactly what that exception is.

**Comment by asklar** [comment]
looks like the xaml `Margin` property is colliding with the react native core [`margin` property](https://reactnative.dev/docs/layout-props#margin) which only supports numbers or strings. 
Going to discuss this more in microsoft/react-native-windows#8158

**Comment by dstaley** [comment]
I'm sure it's the same issue, but `<TextBlock style={{marginBottom: 8}} text="USPS" />` also results in a crash. Just thought I'd mention it in case that's significant.

**Comment by asklar** [comment]
Actually that's a similar but slightly different issue - in that case it looks like RNW is sending the marginBottom property to the react-native-xaml viewmanager, without context that it should be inside of a `style` object

**Comment by asklar** [comment]
This should be fixed in recent versions, we will only assert when we find a property we don't recognize if we are running under the debugger (e.g. in VS). See https://github.com/asklar/react-native-xaml/blob/main/package/windows/ReactNativeXaml/XamlViewManager.cpp#L77
