### ISSUE TITLE
`defaultLabelPosition="collapsed"` renders AppBarButtons without padding

### ISSUE THREAD

**Issue by dstaley** [asklar/react-native-xaml#96]
![image](https://user-images.githubusercontent.com/88163/124640795-c2a91200-de42-11eb-9d89-b51c8676dca7.png)

Rendering a CommandBar with `defaultLabelPosition="collapsed"` causes the AppBarButtons to render without any padding.

**Comment by asklar** [comment]
Bug is in framework, tracking: microsoft/react-native-windows#8213
